version: '3.8.10'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "python /django-resapi/manage.py makemigrations && python /django-resapi/manage.py migrate && python /django-resapi/manage.py runserver 0.0.0.0:8000"
    container_name: django-resapi
    volumes:
      - .:/django-resapi
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes: 
        - postgres_data:/var/lib/postgresql/data/
    environment: 
        - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data: