# Generated by Django 4.1.3 on 2022-11-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='aptitudeResultsMin',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='potentialemployee',
            name='aptitudeResults',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
