# Generated by Django 4.1.3 on 2022-11-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0002_alter_jobapplication_aptituderesultsmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='jobDescription',
            field=models.CharField(default='default job description', max_length=1000),
        ),
    ]
