# Generated by Django 4.1.3 on 2022-11-30 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0003_jobapplication_jobdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialemployee',
            name='jobApplication',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='capstoneapi.jobapplication'),
        ),
    ]
