# Generated by Django 4.1.3 on 2023-02-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0004_potentialemployee_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
