# Generated by Django 4.1.3 on 2023-03-01 11:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0005_jobapplication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company',
            field=models.CharField(default='placeholder_company', max_length=300),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='createdBy',
            field=models.CharField(default='placeholder_createdBy', max_length=30),
        ),
        migrations.AddField(
            model_name='potentialemployee',
            name='email',
            field=models.EmailField(default='placeholder_email', max_length=254),
        ),
        migrations.AddField(
            model_name='potentialemployee',
            name='phoneNumber',
            field=models.CharField(blank=True, default='placeholder_number', max_length=30),
        ),
        migrations.AddField(
            model_name='potentialemployee',
            name='uID',
            field=models.CharField(default='placeholder_uID', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='jobDescription',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='minGPA',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='potentialemployee',
            name='GPA',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='potentialemployee',
            name='pastExperiences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
    ]
