# Generated by Django 4.1.3 on 2023-03-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0006_jobapplication_company_jobapplication_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='aptitudeResultsMin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='potentialemployee',
            name='aptitudeResults',
            field=models.IntegerField(),
        ),
    ]
