# Generated by Django 4.1.3 on 2023-03-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0007_alter_jobapplication_pastexperiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='createdBy',
            field=models.CharField(default='placeholder_createdBy', max_length=30, null=True),
        ),
    ]
