# Generated by Django 4.1.3 on 2023-03-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0007_alter_jobapplication_aptituderesultsmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='aptitudeTest',
            field=models.JSONField(default='placeholder_aptitudeTest'),
        ),
    ]
