# Generated by Django 4.1.3 on 2023-03-24 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0008_jobapplication_aptitudetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialemployee',
            name='aptitudeResults',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='potentialemployee',
            name='jobApplication',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='capstoneapi.jobapplication'),
        ),
    ]
