# Generated by Django 4.1.3 on 2023-03-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0009_alter_potentialemployee_aptituderesults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialemployee',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
