# Generated by Django 4.1.3 on 2022-11-28 23:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=300)),
                ('desiredSkills', models.JSONField()),
                ('minGPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('location', models.CharField(max_length=150)),
                ('pastExperiences', models.JSONField()),
                ('aptitudeResultsMin', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='PotentialEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('location', models.CharField(max_length=150)),
                ('pastExperiences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('aptitudeResults', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
